[env:rpipicow]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board = rpipicow
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient @ ^2.8

extra_scripts = pre:tools/gen_build_config.py
