#pragma once
// Auto-generated by tools/gen_build_config.py from environment variables
#define WIFI_SSID ""
#define WIFI_PASS ""
#define MQTT_BROKER ""
#define MQTT_USER ""
#define MQTT_PASS ""
#define MQTT_BASE_TOPIC "rv/pico1"
#define MQTT_DISCOVERY_ENABLED 0
