\
Import("env")
import os

def _get(name, default=""):
    return os.environ.get(name, default)

ssid = _get("WIFI_SSID", "")
pwd  = _get("WIFI_PASS", "")
broker = _get("MQTT_BROKER", "")
disc = _get("MQTT_DISCOVERY", "0")
mqtt_user = _get("MQTT_USER", "")
mqtt_pass = _get("MQTT_PASS", "")
base_topic = _get("MQTT_BASE_TOPIC", "rv/pico1")

# Normalize discovery flag
disc_flag = "1" if str(disc).strip().lower() in ["1","true","yes","on"] else "0"

out_path = env.subst("$PROJECT_INCLUDE_DIR") + "/build_config.h"

hdr = []
hdr.append("#pragma once")
hdr.append("// Auto-generated by tools/gen_build_config.py from environment variables")
hdr.append(f'#define WIFI_SSID "{ssid}"')
hdr.append(f'#define WIFI_PASS "{pwd}"')
hdr.append(f'#define MQTT_BROKER "{broker}"')
hdr.append(f'#define MQTT_USER "{mqtt_user}"')
hdr.append(f'#define MQTT_PASS "{mqtt_pass}"')
hdr.append(f'#define MQTT_BASE_TOPIC "{base_topic}"')
hdr.append(f"#define MQTT_DISCOVERY_ENABLED {disc_flag}")

# Basic guardrails
if not ssid:
    print("[gen_build_config] WIFI_SSID is empty (set WIFI_SSID in your shell env)")
if not broker:
    print("[gen_build_config] MQTT_BROKER is empty (MQTT will be disabled)")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(hdr) + "\n")

print(f"[gen_build_config] wrote {out_path}")
